Use elm.srcObject instead of URL.createObjectURL (#73)
teamious/react-conf-webrtc pull request #84
Opened 2017-08-18 10:32 UTC by ekoneko

2017-08-18 17:12 UTC, asinner requested changes

2017-08-18 17:12 UTC, asinner commented on src/components/controls/Stream.tsx
> +                    ref={(node: HTMLVideoElement) => this.videoRef = node}
don't use anonymous function, use a named function instead. 

`ref={this.refVideo}`

and: 

```tsx
constructor() {
  super()
  this.refVideo = this.refVideo.bind(this)
}
```

2017-08-18 17:12 UTC, asinner commented on src/components/controls/Stream.tsx
> +    videoRef: HTMLVideoElement;
Make `private`

2017-08-19 01:11 UTC, ekoneko commented on src/components/controls/Stream.tsx
> +                    ref={(node: HTMLVideoElement) => this.videoRef = node}
The `refVideo` method and `videoRef` element seem weird.
I want to use `videoElement` instead of `videoRef`. That's ok?

2017-08-21 22:57 UTC, asinner approved these changes

2017-08-21 22:57 UTC, asinner commented on src/components/controls/Stream.tsx
> +        this.videoElement = this.videoElement = element;
`this.videoElement = element`

2017-08-22 02:43 UTC, linweigao approved these changes

2017-08-22 17:09 UTC, merged